# Generated by Django 5.0.4 on 2024-06-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprint', '0002_alter_blueprint_options_remove_blueprint_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blueprint',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='file_b3d',
            field=models.FileField(blank=True, null=True, upload_to='blueprints/b3d'),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='file_dwg',
            field=models.FileField(blank=True, null=True, upload_to='blueprints/dwg'),
        ),
    ]
