# Generated by Django 5.0.4 on 2024-06-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completed_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentswork',
            name='comment',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='commentswork',
            name='completed_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='completed_work.completedwork'),
        ),
    ]
