# Generated by Django 5.0.4 on 2024-06-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completed_work', '0002_alter_commentswork_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentswork',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='completedwork',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='fotowork',
            name='completed_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='completed_work.completedwork'),
        ),
        migrations.AlterField(
            model_name='fotowork',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
